dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

networks:
  mainnet:
    - eth-usd-feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  rinkeby:
    - eth-usd-feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
  kovan:
    - eth-usd-feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
